export const emptyOperatingData = {
  live: false,
  sites: [],
  buildings: [],
  spaces: [],
  assets: [],
  requests: [],
  workOrders: [],
  workOrdersTotal: 0,
  inventory: [],
  inspections: [],
  alerts: [],
  teams: [],
  services: [],
  categories: [],
  ppms: [],
  ppmsTotal: 0,
  users: [],
  permissions: [],
  departments: [],
  employees: [],
  rolePermissions: [],
  locations: [],
  jobPlans: [],
  jobPlansTotal: 0,
  roles: [],
  auditLogs: [],
  complianceCertificates: [],
  documentUploads: [],
  totalEntries: {},
  dashboardStats: {
    workOrders: { total: 0, open: 0, inProgress: 0, completed: 0 },
    serviceRequests: { total: 0, open: 0 },
    incidents: { total: 0 },
    assets: { total: 0, active: 0, criticalHigh: 0 },
    inventory: { totalItems: 0, onHandUnits: 0 },
    ppm: { total: 0, active: 0, due: 0 },
    housing: {
      bookingsTotal: 0,
      currentGuests: 0,
      reserved: 0,
      checkedOut: 0,
      roomsTotal: 0,
      vacantRooms: 0,
      occupiedRooms: 0,
    },
    compliance: { total: 0 },
    documents: { total: 0 },
    lostFound: { total: 0 },
    security: { gatePasses: 0, reports: 0, total: 0 },
  },
  shiftRotation: {
    shifts: [],
    rotations: [],
    roster: [],
  },
  security: {
    locations: [],
    gatePasses: [],
    dailyReports: [],
    fireDrills: [],
    checklists: [],
  },
  housing: {
    properties: [],
    blocks: [],
    rooms: [],
    beds: [],
    residents: [],
    bookings: [],
    inspections: [],
    assets: [],
    inventory: [],
    approvals: [],
    notifications: [],
    holds: [],
    notificationSettings: [],
    history: [],
  },
};
