ALTER TABLE "RolePermission" ADD COLUMN IF NOT EXISTS "scope" TEXT NOT NULL DEFAULT 'Company';
CREATE INDEX IF NOT EXISTS "RolePermission_role_scope_idx" ON "RolePermission"("role", "scope");

INSERT INTO "Permission" ("id", "code", "name", "module", "description")
SELECT CONCAT('perm_', REPLACE(v.code, '.', '_')), v.code, v.name, v.module, v.description
FROM (VALUES
('dashboard.view','View Dashboard','Dashboard','View access for Dashboard.'),
('dashboard.create','Create Dashboard','Dashboard','Create access for Dashboard.'),
('dashboard.edit','Edit Dashboard','Dashboard','Edit access for Dashboard.'),
('dashboard.delete','Delete Dashboard','Dashboard','Delete access for Dashboard.'),
('dashboard.approve','Approve Dashboard','Dashboard','Approve access for Dashboard.'),
('dashboard.assign','Assign Dashboard','Dashboard','Assign access for Dashboard.'),
('dashboard.import','Import Dashboard','Dashboard','Import access for Dashboard.'),
('dashboard.export','Export Dashboard','Dashboard','Export access for Dashboard.'),
('dashboard.report','Report Dashboard','Dashboard','Report access for Dashboard.'),
('dashboard.settings','Settings Dashboard','Dashboard','Settings access for Dashboard.'),
('dashboard.dashboard','Dashboard Dashboard','Dashboard','Dashboard access for Dashboard.'),
('assets.view','View Assets','Assets','View access for Assets.'),
('assets.create','Create Assets','Assets','Create access for Assets.'),
('assets.edit','Edit Assets','Assets','Edit access for Assets.'),
('assets.delete','Delete Assets','Assets','Delete access for Assets.'),
('assets.approve','Approve Assets','Assets','Approve access for Assets.'),
('assets.assign','Assign Assets','Assets','Assign access for Assets.'),
('assets.import','Import Assets','Assets','Import access for Assets.'),
('assets.export','Export Assets','Assets','Export access for Assets.'),
('assets.report','Report Assets','Assets','Report access for Assets.'),
('assets.settings','Settings Assets','Assets','Settings access for Assets.'),
('assets.dashboard','Dashboard Assets','Assets','Dashboard access for Assets.'),
('locations.view','View Locations','Locations','View access for Locations.'),
('locations.create','Create Locations','Locations','Create access for Locations.'),
('locations.edit','Edit Locations','Locations','Edit access for Locations.'),
('locations.delete','Delete Locations','Locations','Delete access for Locations.'),
('locations.approve','Approve Locations','Locations','Approve access for Locations.'),
('locations.assign','Assign Locations','Locations','Assign access for Locations.'),
('locations.import','Import Locations','Locations','Import access for Locations.'),
('locations.export','Export Locations','Locations','Export access for Locations.'),
('locations.report','Report Locations','Locations','Report access for Locations.'),
('locations.settings','Settings Locations','Locations','Settings access for Locations.'),
('locations.dashboard','Dashboard Locations','Locations','Dashboard access for Locations.'),
('workorders.view','View Work Orders','Work Orders','View access for Work Orders.'),
('workorders.create','Create Work Orders','Work Orders','Create access for Work Orders.'),
('workorders.edit','Edit Work Orders','Work Orders','Edit access for Work Orders.'),
('workorders.delete','Delete Work Orders','Work Orders','Delete access for Work Orders.'),
('workorders.approve','Approve Work Orders','Work Orders','Approve access for Work Orders.'),
('workorders.assign','Assign Work Orders','Work Orders','Assign access for Work Orders.'),
('workorders.import','Import Work Orders','Work Orders','Import access for Work Orders.'),
('workorders.export','Export Work Orders','Work Orders','Export access for Work Orders.'),
('workorders.report','Report Work Orders','Work Orders','Report access for Work Orders.'),
('workorders.settings','Settings Work Orders','Work Orders','Settings access for Work Orders.'),
('workorders.dashboard','Dashboard Work Orders','Work Orders','Dashboard access for Work Orders.'),
('servicerequests.view','View Service Requests','Service Requests','View access for Service Requests.'),
('servicerequests.create','Create Service Requests','Service Requests','Create access for Service Requests.'),
('servicerequests.edit','Edit Service Requests','Service Requests','Edit access for Service Requests.'),
('servicerequests.delete','Delete Service Requests','Service Requests','Delete access for Service Requests.'),
('servicerequests.approve','Approve Service Requests','Service Requests','Approve access for Service Requests.'),
('servicerequests.assign','Assign Service Requests','Service Requests','Assign access for Service Requests.'),
('servicerequests.import','Import Service Requests','Service Requests','Import access for Service Requests.'),
('servicerequests.export','Export Service Requests','Service Requests','Export access for Service Requests.'),
('servicerequests.report','Report Service Requests','Service Requests','Report access for Service Requests.'),
('servicerequests.settings','Settings Service Requests','Service Requests','Settings access for Service Requests.'),
('servicerequests.dashboard','Dashboard Service Requests','Service Requests','Dashboard access for Service Requests.'),
('ppm.view','View PPM','PPM','View access for PPM.'),
('ppm.create','Create PPM','PPM','Create access for PPM.'),
('ppm.edit','Edit PPM','PPM','Edit access for PPM.'),
('ppm.delete','Delete PPM','PPM','Delete access for PPM.'),
('ppm.approve','Approve PPM','PPM','Approve access for PPM.'),
('ppm.assign','Assign PPM','PPM','Assign access for PPM.'),
('ppm.import','Import PPM','PPM','Import access for PPM.'),
('ppm.export','Export PPM','PPM','Export access for PPM.'),
('ppm.report','Report PPM','PPM','Report access for PPM.'),
('ppm.settings','Settings PPM','PPM','Settings access for PPM.'),
('ppm.dashboard','Dashboard PPM','PPM','Dashboard access for PPM.'),
('inventory.view','View Inventory','Inventory','View access for Inventory.'),
('inventory.create','Create Inventory','Inventory','Create access for Inventory.'),
('inventory.edit','Edit Inventory','Inventory','Edit access for Inventory.'),
('inventory.delete','Delete Inventory','Inventory','Delete access for Inventory.'),
('inventory.approve','Approve Inventory','Inventory','Approve access for Inventory.'),
('inventory.assign','Assign Inventory','Inventory','Assign access for Inventory.'),
('inventory.import','Import Inventory','Inventory','Import access for Inventory.'),
('inventory.export','Export Inventory','Inventory','Export access for Inventory.'),
('inventory.report','Report Inventory','Inventory','Report access for Inventory.'),
('inventory.settings','Settings Inventory','Inventory','Settings access for Inventory.'),
('inventory.dashboard','Dashboard Inventory','Inventory','Dashboard access for Inventory.'),
('safety.view','View Safety','Safety','View access for Safety.'),
('safety.create','Create Safety','Safety','Create access for Safety.'),
('safety.edit','Edit Safety','Safety','Edit access for Safety.'),
('safety.delete','Delete Safety','Safety','Delete access for Safety.'),
('safety.approve','Approve Safety','Safety','Approve access for Safety.'),
('safety.assign','Assign Safety','Safety','Assign access for Safety.'),
('safety.import','Import Safety','Safety','Import access for Safety.'),
('safety.export','Export Safety','Safety','Export access for Safety.'),
('safety.report','Report Safety','Safety','Report access for Safety.'),
('safety.settings','Settings Safety','Safety','Settings access for Safety.'),
('safety.dashboard','Dashboard Safety','Safety','Dashboard access for Safety.'),
('incidents.view','View Incidents','Incidents','View access for Incidents.'),
('incidents.create','Create Incidents','Incidents','Create access for Incidents.'),
('incidents.edit','Edit Incidents','Incidents','Edit access for Incidents.'),
('incidents.delete','Delete Incidents','Incidents','Delete access for Incidents.'),
('incidents.approve','Approve Incidents','Incidents','Approve access for Incidents.'),
('incidents.assign','Assign Incidents','Incidents','Assign access for Incidents.'),
('incidents.import','Import Incidents','Incidents','Import access for Incidents.'),
('incidents.export','Export Incidents','Incidents','Export access for Incidents.'),
('incidents.report','Report Incidents','Incidents','Report access for Incidents.'),
('incidents.settings','Settings Incidents','Incidents','Settings access for Incidents.'),
('incidents.dashboard','Dashboard Incidents','Incidents','Dashboard access for Incidents.'),
('compliance.view','View Compliance','Compliance','View access for Compliance.'),
('compliance.create','Create Compliance','Compliance','Create access for Compliance.'),
('compliance.edit','Edit Compliance','Compliance','Edit access for Compliance.'),
('compliance.delete','Delete Compliance','Compliance','Delete access for Compliance.'),
('compliance.approve','Approve Compliance','Compliance','Approve access for Compliance.'),
('compliance.assign','Assign Compliance','Compliance','Assign access for Compliance.'),
('compliance.import','Import Compliance','Compliance','Import access for Compliance.'),
('compliance.export','Export Compliance','Compliance','Export access for Compliance.'),
('compliance.report','Report Compliance','Compliance','Report access for Compliance.'),
('compliance.settings','Settings Compliance','Compliance','Settings access for Compliance.'),
('compliance.dashboard','Dashboard Compliance','Compliance','Dashboard access for Compliance.'),
('certifications.view','View Certifications','Certifications','View access for Certifications.'),
('certifications.create','Create Certifications','Certifications','Create access for Certifications.'),
('certifications.edit','Edit Certifications','Certifications','Edit access for Certifications.'),
('certifications.delete','Delete Certifications','Certifications','Delete access for Certifications.'),
('certifications.approve','Approve Certifications','Certifications','Approve access for Certifications.'),
('certifications.assign','Assign Certifications','Certifications','Assign access for Certifications.'),
('certifications.import','Import Certifications','Certifications','Import access for Certifications.'),
('certifications.export','Export Certifications','Certifications','Export access for Certifications.'),
('certifications.report','Report Certifications','Certifications','Report access for Certifications.'),
('certifications.settings','Settings Certifications','Certifications','Settings access for Certifications.'),
('certifications.dashboard','Dashboard Certifications','Certifications','Dashboard access for Certifications.'),
('documents.view','View Documents','Documents','View access for Documents.'),
('documents.create','Create Documents','Documents','Create access for Documents.'),
('documents.edit','Edit Documents','Documents','Edit access for Documents.'),
('documents.delete','Delete Documents','Documents','Delete access for Documents.'),
('documents.approve','Approve Documents','Documents','Approve access for Documents.'),
('documents.assign','Assign Documents','Documents','Assign access for Documents.'),
('documents.import','Import Documents','Documents','Import access for Documents.'),
('documents.export','Export Documents','Documents','Export access for Documents.'),
('documents.report','Report Documents','Documents','Report access for Documents.'),
('documents.settings','Settings Documents','Documents','Settings access for Documents.'),
('documents.dashboard','Dashboard Documents','Documents','Dashboard access for Documents.'),
('housing.view','View Housing','Housing','View access for Housing.'),
('housing.create','Create Housing','Housing','Create access for Housing.'),
('housing.edit','Edit Housing','Housing','Edit access for Housing.'),
('housing.delete','Delete Housing','Housing','Delete access for Housing.'),
('housing.approve','Approve Housing','Housing','Approve access for Housing.'),
('housing.assign','Assign Housing','Housing','Assign access for Housing.'),
('housing.import','Import Housing','Housing','Import access for Housing.'),
('housing.export','Export Housing','Housing','Export access for Housing.'),
('housing.report','Report Housing','Housing','Report access for Housing.'),
('housing.settings','Settings Housing','Housing','Settings access for Housing.'),
('housing.dashboard','Dashboard Housing','Housing','Dashboard access for Housing.'),
('residents.view','View Residents','Residents','View access for Residents.'),
('residents.create','Create Residents','Residents','Create access for Residents.'),
('residents.edit','Edit Residents','Residents','Edit access for Residents.'),
('residents.delete','Delete Residents','Residents','Delete access for Residents.'),
('residents.approve','Approve Residents','Residents','Approve access for Residents.'),
('residents.assign','Assign Residents','Residents','Assign access for Residents.'),
('residents.import','Import Residents','Residents','Import access for Residents.'),
('residents.export','Export Residents','Residents','Export access for Residents.'),
('residents.report','Report Residents','Residents','Report access for Residents.'),
('residents.settings','Settings Residents','Residents','Settings access for Residents.'),
('residents.dashboard','Dashboard Residents','Residents','Dashboard access for Residents.'),
('reports.view','View Reports','Reports','View access for Reports.'),
('reports.create','Create Reports','Reports','Create access for Reports.'),
('reports.edit','Edit Reports','Reports','Edit access for Reports.'),
('reports.delete','Delete Reports','Reports','Delete access for Reports.'),
('reports.approve','Approve Reports','Reports','Approve access for Reports.'),
('reports.assign','Assign Reports','Reports','Assign access for Reports.'),
('reports.import','Import Reports','Reports','Import access for Reports.'),
('reports.export','Export Reports','Reports','Export access for Reports.'),
('reports.report','Report Reports','Reports','Report access for Reports.'),
('reports.settings','Settings Reports','Reports','Settings access for Reports.'),
('reports.dashboard','Dashboard Reports','Reports','Dashboard access for Reports.'),
('users.view','View Users','Users','View access for Users.'),
('users.create','Create Users','Users','Create access for Users.'),
('users.edit','Edit Users','Users','Edit access for Users.'),
('users.delete','Delete Users','Users','Delete access for Users.'),
('users.approve','Approve Users','Users','Approve access for Users.'),
('users.assign','Assign Users','Users','Assign access for Users.'),
('users.import','Import Users','Users','Import access for Users.'),
('users.export','Export Users','Users','Export access for Users.'),
('users.report','Report Users','Users','Report access for Users.'),
('users.settings','Settings Users','Users','Settings access for Users.'),
('users.dashboard','Dashboard Users','Users','Dashboard access for Users.'),
('roles.view','View Roles','Roles','View access for Roles.'),
('roles.create','Create Roles','Roles','Create access for Roles.'),
('roles.edit','Edit Roles','Roles','Edit access for Roles.'),
('roles.delete','Delete Roles','Roles','Delete access for Roles.'),
('roles.approve','Approve Roles','Roles','Approve access for Roles.'),
('roles.assign','Assign Roles','Roles','Assign access for Roles.'),
('roles.import','Import Roles','Roles','Import access for Roles.'),
('roles.export','Export Roles','Roles','Export access for Roles.'),
('roles.report','Report Roles','Roles','Report access for Roles.'),
('roles.settings','Settings Roles','Roles','Settings access for Roles.'),
('roles.dashboard','Dashboard Roles','Roles','Dashboard access for Roles.'),
('settings.view','View Settings','Settings','View access for Settings.'),
('settings.create','Create Settings','Settings','Create access for Settings.'),
('settings.edit','Edit Settings','Settings','Edit access for Settings.'),
('settings.delete','Delete Settings','Settings','Delete access for Settings.'),
('settings.approve','Approve Settings','Settings','Approve access for Settings.'),
('settings.assign','Assign Settings','Settings','Assign access for Settings.'),
('settings.import','Import Settings','Settings','Import access for Settings.'),
('settings.export','Export Settings','Settings','Export access for Settings.'),
('settings.report','Report Settings','Settings','Report access for Settings.'),
('settings.settings','Settings Settings','Settings','Settings access for Settings.'),
('settings.dashboard','Dashboard Settings','Settings','Dashboard access for Settings.')
) AS v(code, name, module, description)
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "module" = EXCLUDED."module",
  "description" = EXCLUDED."description";

INSERT INTO "Role" ("id", "name", "description", "standard")
SELECT CONCAT('role_', LOWER(REGEXP_REPLACE(v.name, '[^a-zA-Z0-9]+', '_', 'g'))), v.name, v.description, v.standard
FROM (VALUES
('Admin','Admin standard CAFM role',true),
('Facility Manager','Facility Manager standard CAFM role',true),
('Maintenance Manager','Maintenance Manager standard CAFM role',true),
('Department Supervisor','Department Supervisor standard CAFM role',true),
('Supervisor','Supervisor standard CAFM role',true),
('Service Team','Service Team standard CAFM role',true),
('Technician','Technician standard CAFM role',true),
('Helpdesk','Helpdesk standard CAFM role',true),
('Reception','Reception standard CAFM role',true),
('Storekeeper','Storekeeper standard CAFM role',true),
('HSE Officer','HSE Officer standard CAFM role',true),
('Compliance Officer','Compliance Officer standard CAFM role',true),
('Housing Manager','Housing Manager standard CAFM role',true),
('Resident','Resident standard CAFM role',true),
('Requester','Requester standard CAFM role',true),
('Read-only','Read-only standard CAFM role',true)
) AS v(name, description, standard)
ON CONFLICT ("name") DO UPDATE SET
  "description" = EXCLUDED."description",
  "standard" = true;

INSERT INTO "RolePermission" ("id", "role", "permissionId", "scope")
SELECT CONCAT('rp_', LOWER(REGEXP_REPLACE(v.role, '[^a-zA-Z0-9]+', '_', 'g')), '_', REPLACE(v.code, '.', '_')), v.role, p."id", v.scope
FROM (VALUES
('Admin','dashboard.view','Global'),
('Admin','dashboard.create','Global'),
('Admin','dashboard.edit','Global'),
('Admin','dashboard.delete','Global'),
('Admin','dashboard.approve','Global'),
('Admin','dashboard.assign','Global'),
('Admin','dashboard.import','Global'),
('Admin','dashboard.export','Global'),
('Admin','dashboard.report','Global'),
('Admin','dashboard.settings','Global'),
('Admin','dashboard.dashboard','Global'),
('Admin','assets.view','Global'),
('Admin','assets.create','Global'),
('Admin','assets.edit','Global'),
('Admin','assets.delete','Global'),
('Admin','assets.approve','Global'),
('Admin','assets.assign','Global'),
('Admin','assets.import','Global'),
('Admin','assets.export','Global'),
('Admin','assets.report','Global'),
('Admin','assets.settings','Global'),
('Admin','assets.dashboard','Global'),
('Admin','locations.view','Global'),
('Admin','locations.create','Global'),
('Admin','locations.edit','Global'),
('Admin','locations.delete','Global'),
('Admin','locations.approve','Global'),
('Admin','locations.assign','Global'),
('Admin','locations.import','Global'),
('Admin','locations.export','Global'),
('Admin','locations.report','Global'),
('Admin','locations.settings','Global'),
('Admin','locations.dashboard','Global'),
('Admin','workorders.view','Global'),
('Admin','workorders.create','Global'),
('Admin','workorders.edit','Global'),
('Admin','workorders.delete','Global'),
('Admin','workorders.approve','Global'),
('Admin','workorders.assign','Global'),
('Admin','workorders.import','Global'),
('Admin','workorders.export','Global'),
('Admin','workorders.report','Global'),
('Admin','workorders.settings','Global'),
('Admin','workorders.dashboard','Global'),
('Admin','servicerequests.view','Global'),
('Admin','servicerequests.create','Global'),
('Admin','servicerequests.edit','Global'),
('Admin','servicerequests.delete','Global'),
('Admin','servicerequests.approve','Global'),
('Admin','servicerequests.assign','Global'),
('Admin','servicerequests.import','Global'),
('Admin','servicerequests.export','Global'),
('Admin','servicerequests.report','Global'),
('Admin','servicerequests.settings','Global'),
('Admin','servicerequests.dashboard','Global'),
('Admin','ppm.view','Global'),
('Admin','ppm.create','Global'),
('Admin','ppm.edit','Global'),
('Admin','ppm.delete','Global'),
('Admin','ppm.approve','Global'),
('Admin','ppm.assign','Global'),
('Admin','ppm.import','Global'),
('Admin','ppm.export','Global'),
('Admin','ppm.report','Global'),
('Admin','ppm.settings','Global'),
('Admin','ppm.dashboard','Global'),
('Admin','inventory.view','Global'),
('Admin','inventory.create','Global'),
('Admin','inventory.edit','Global'),
('Admin','inventory.delete','Global'),
('Admin','inventory.approve','Global'),
('Admin','inventory.assign','Global'),
('Admin','inventory.import','Global'),
('Admin','inventory.export','Global'),
('Admin','inventory.report','Global'),
('Admin','inventory.settings','Global'),
('Admin','inventory.dashboard','Global'),
('Admin','safety.view','Global'),
('Admin','safety.create','Global'),
('Admin','safety.edit','Global'),
('Admin','safety.delete','Global'),
('Admin','safety.approve','Global'),
('Admin','safety.assign','Global'),
('Admin','safety.import','Global'),
('Admin','safety.export','Global'),
('Admin','safety.report','Global'),
('Admin','safety.settings','Global'),
('Admin','safety.dashboard','Global'),
('Admin','incidents.view','Global'),
('Admin','incidents.create','Global'),
('Admin','incidents.edit','Global'),
('Admin','incidents.delete','Global'),
('Admin','incidents.approve','Global'),
('Admin','incidents.assign','Global'),
('Admin','incidents.import','Global'),
('Admin','incidents.export','Global'),
('Admin','incidents.report','Global'),
('Admin','incidents.settings','Global'),
('Admin','incidents.dashboard','Global'),
('Admin','compliance.view','Global'),
('Admin','compliance.create','Global'),
('Admin','compliance.edit','Global'),
('Admin','compliance.delete','Global'),
('Admin','compliance.approve','Global'),
('Admin','compliance.assign','Global'),
('Admin','compliance.import','Global'),
('Admin','compliance.export','Global'),
('Admin','compliance.report','Global'),
('Admin','compliance.settings','Global'),
('Admin','compliance.dashboard','Global'),
('Admin','certifications.view','Global'),
('Admin','certifications.create','Global'),
('Admin','certifications.edit','Global'),
('Admin','certifications.delete','Global'),
('Admin','certifications.approve','Global'),
('Admin','certifications.assign','Global'),
('Admin','certifications.import','Global'),
('Admin','certifications.export','Global'),
('Admin','certifications.report','Global'),
('Admin','certifications.settings','Global'),
('Admin','certifications.dashboard','Global'),
('Admin','documents.view','Global'),
('Admin','documents.create','Global'),
('Admin','documents.edit','Global'),
('Admin','documents.delete','Global'),
('Admin','documents.approve','Global'),
('Admin','documents.assign','Global'),
('Admin','documents.import','Global'),
('Admin','documents.export','Global'),
('Admin','documents.report','Global'),
('Admin','documents.settings','Global'),
('Admin','documents.dashboard','Global'),
('Admin','housing.view','Global'),
('Admin','housing.create','Global'),
('Admin','housing.edit','Global'),
('Admin','housing.delete','Global'),
('Admin','housing.approve','Global'),
('Admin','housing.assign','Global'),
('Admin','housing.import','Global'),
('Admin','housing.export','Global'),
('Admin','housing.report','Global'),
('Admin','housing.settings','Global'),
('Admin','housing.dashboard','Global'),
('Admin','residents.view','Global'),
('Admin','residents.create','Global'),
('Admin','residents.edit','Global'),
('Admin','residents.delete','Global'),
('Admin','residents.approve','Global'),
('Admin','residents.assign','Global'),
('Admin','residents.import','Global'),
('Admin','residents.export','Global'),
('Admin','residents.report','Global'),
('Admin','residents.settings','Global'),
('Admin','residents.dashboard','Global'),
('Admin','reports.view','Global'),
('Admin','reports.create','Global'),
('Admin','reports.edit','Global'),
('Admin','reports.delete','Global'),
('Admin','reports.approve','Global'),
('Admin','reports.assign','Global'),
('Admin','reports.import','Global'),
('Admin','reports.export','Global'),
('Admin','reports.report','Global'),
('Admin','reports.settings','Global'),
('Admin','reports.dashboard','Global'),
('Admin','users.view','Global'),
('Admin','users.create','Global'),
('Admin','users.edit','Global'),
('Admin','users.delete','Global'),
('Admin','users.approve','Global'),
('Admin','users.assign','Global'),
('Admin','users.import','Global'),
('Admin','users.export','Global'),
('Admin','users.report','Global'),
('Admin','users.settings','Global'),
('Admin','users.dashboard','Global'),
('Admin','roles.view','Global'),
('Admin','roles.create','Global'),
('Admin','roles.edit','Global'),
('Admin','roles.delete','Global'),
('Admin','roles.approve','Global'),
('Admin','roles.assign','Global'),
('Admin','roles.import','Global'),
('Admin','roles.export','Global'),
('Admin','roles.report','Global'),
('Admin','roles.settings','Global'),
('Admin','roles.dashboard','Global'),
('Admin','settings.view','Global'),
('Admin','settings.create','Global'),
('Admin','settings.edit','Global'),
('Admin','settings.delete','Global'),
('Admin','settings.approve','Global'),
('Admin','settings.assign','Global'),
('Admin','settings.import','Global'),
('Admin','settings.export','Global'),
('Admin','settings.report','Global'),
('Admin','settings.settings','Global'),
('Admin','settings.dashboard','Global'),
('Facility Manager','dashboard.view','Company'),
('Facility Manager','assets.view','Company'),
('Facility Manager','assets.create','Company'),
('Facility Manager','assets.edit','Company'),
('Facility Manager','assets.import','Company'),
('Facility Manager','assets.export','Company'),
('Facility Manager','assets.report','Company'),
('Facility Manager','locations.view','Company'),
('Facility Manager','locations.create','Company'),
('Facility Manager','locations.edit','Company'),
('Facility Manager','workorders.view','Company'),
('Facility Manager','workorders.create','Company'),
('Facility Manager','workorders.edit','Company'),
('Facility Manager','workorders.assign','Company'),
('Facility Manager','workorders.approve','Company'),
('Facility Manager','workorders.report','Company'),
('Facility Manager','servicerequests.view','Company'),
('Facility Manager','servicerequests.create','Company'),
('Facility Manager','servicerequests.edit','Company'),
('Facility Manager','servicerequests.assign','Company'),
('Facility Manager','servicerequests.approve','Company'),
('Facility Manager','ppm.view','Company'),
('Facility Manager','ppm.create','Company'),
('Facility Manager','ppm.edit','Company'),
('Facility Manager','ppm.report','Company'),
('Facility Manager','inventory.view','Company'),
('Facility Manager','safety.view','Company'),
('Facility Manager','incidents.view','Company'),
('Facility Manager','compliance.view','Company'),
('Facility Manager','certifications.view','Company'),
('Facility Manager','housing.view','Company'),
('Facility Manager','reports.view','Company'),
('Facility Manager','reports.export','Company'),
('Maintenance Manager','dashboard.view','Facility'),
('Maintenance Manager','assets.view','Facility'),
('Maintenance Manager','assets.create','Facility'),
('Maintenance Manager','assets.edit','Facility'),
('Maintenance Manager','assets.import','Facility'),
('Maintenance Manager','workorders.view','Facility'),
('Maintenance Manager','workorders.create','Facility'),
('Maintenance Manager','workorders.edit','Facility'),
('Maintenance Manager','workorders.assign','Facility'),
('Maintenance Manager','workorders.approve','Facility'),
('Maintenance Manager','ppm.view','Facility'),
('Maintenance Manager','ppm.create','Facility'),
('Maintenance Manager','ppm.edit','Facility'),
('Maintenance Manager','inventory.view','Facility'),
('Maintenance Manager','reports.view','Facility'),
('Maintenance Manager','reports.export','Facility'),
('Department Supervisor','dashboard.view','Department'),
('Department Supervisor','assets.view','Department'),
('Department Supervisor','workorders.view','Department'),
('Department Supervisor','workorders.create','Department'),
('Department Supervisor','workorders.edit','Department'),
('Department Supervisor','workorders.assign','Department'),
('Department Supervisor','workorders.approve','Department'),
('Department Supervisor','servicerequests.view','Department'),
('Department Supervisor','servicerequests.create','Department'),
('Department Supervisor','servicerequests.edit','Department'),
('Department Supervisor','servicerequests.assign','Department'),
('Department Supervisor','servicerequests.approve','Department'),
('Department Supervisor','ppm.view','Department'),
('Department Supervisor','reports.view','Department'),
('Supervisor','dashboard.view','Department'),
('Supervisor','assets.view','Department'),
('Supervisor','workorders.view','Department'),
('Supervisor','workorders.create','Department'),
('Supervisor','workorders.edit','Department'),
('Supervisor','workorders.assign','Department'),
('Supervisor','workorders.approve','Department'),
('Supervisor','servicerequests.view','Department'),
('Supervisor','servicerequests.edit','Department'),
('Supervisor','servicerequests.assign','Department'),
('Supervisor','servicerequests.approve','Department'),
('Supervisor','reports.view','Department'),
('Service Team','assets.view','Own'),
('Service Team','workorders.view','Own'),
('Service Team','workorders.edit','Own'),
('Service Team','servicerequests.view','Own'),
('Technician','assets.view','Own'),
('Technician','workorders.view','Own'),
('Technician','workorders.edit','Own'),
('Technician','servicerequests.view','Own'),
('Helpdesk','dashboard.view','Company'),
('Helpdesk','servicerequests.view','Company'),
('Helpdesk','servicerequests.create','Company'),
('Helpdesk','servicerequests.edit','Company'),
('Helpdesk','servicerequests.assign','Company'),
('Helpdesk','workorders.view','Company'),
('Helpdesk','assets.view','Company'),
('Reception','servicerequests.view','Facility'),
('Reception','servicerequests.create','Facility'),
('Reception','residents.view','Facility'),
('Reception','housing.view','Facility'),
('Storekeeper','inventory.view','Facility'),
('Storekeeper','inventory.create','Facility'),
('Storekeeper','inventory.edit','Facility'),
('Storekeeper','inventory.import','Facility'),
('Storekeeper','inventory.export','Facility'),
('Storekeeper','inventory.report','Facility'),
('Storekeeper','workorders.view','Facility'),
('Storekeeper','assets.view','Facility'),
('HSE Officer','safety.view','Company'),
('HSE Officer','safety.create','Company'),
('HSE Officer','safety.edit','Company'),
('HSE Officer','safety.report','Company'),
('HSE Officer','incidents.view','Company'),
('HSE Officer','incidents.create','Company'),
('HSE Officer','incidents.edit','Company'),
('HSE Officer','incidents.approve','Company'),
('HSE Officer','reports.view','Company'),
('Compliance Officer','compliance.view','Company'),
('Compliance Officer','compliance.create','Company'),
('Compliance Officer','compliance.edit','Company'),
('Compliance Officer','compliance.delete','Company'),
('Compliance Officer','compliance.report','Company'),
('Compliance Officer','certifications.view','Company'),
('Compliance Officer','certifications.create','Company'),
('Compliance Officer','certifications.edit','Company'),
('Compliance Officer','certifications.report','Company'),
('Compliance Officer','reports.view','Company'),
('Housing Manager','housing.view','Facility'),
('Housing Manager','housing.create','Facility'),
('Housing Manager','housing.edit','Facility'),
('Housing Manager','housing.delete','Facility'),
('Housing Manager','housing.approve','Facility'),
('Housing Manager','housing.report','Facility'),
('Housing Manager','residents.view','Facility'),
('Housing Manager','residents.create','Facility'),
('Housing Manager','residents.edit','Facility'),
('Housing Manager','servicerequests.view','Facility'),
('Housing Manager','reports.view','Facility'),
('Resident','servicerequests.view','Own'),
('Resident','servicerequests.create','Own'),
('Requester','servicerequests.view','Own'),
('Requester','servicerequests.create','Own'),
('Read-only','dashboard.view','Company'),
('Read-only','assets.view','Company'),
('Read-only','locations.view','Company'),
('Read-only','workorders.view','Company'),
('Read-only','servicerequests.view','Company'),
('Read-only','ppm.view','Company'),
('Read-only','inventory.view','Company'),
('Read-only','safety.view','Company'),
('Read-only','incidents.view','Company'),
('Read-only','compliance.view','Company'),
('Read-only','certifications.view','Company'),
('Read-only','documents.view','Company'),
('Read-only','housing.view','Company'),
('Read-only','residents.view','Company'),
('Read-only','reports.view','Company')
) AS v(role, code, scope)
JOIN "Permission" p ON p."code" = v.code
ON CONFLICT ("role", "permissionId") DO UPDATE SET "scope" = EXCLUDED."scope";
